### ISSUE TITLE
AIAAException: (3, "Status: 403; Response: b''")

### ISSUE THREAD

**Issue by st084331** [NVIDIA/ai-assisted-annotation-client#106]
Hello, everyone. I want to start working with AIAAclient and I have an error in the second line of the code:

client = client_api.AIAAClient(server_url='http://0.0.0.0:5000')
models = client.model_list(label='spleen')

Terminal:
Traceback (most recent call last):
  File "/Users/akabynda/Diffuse_Steatoch/main.py", line 254, in <module>
    models = client.model_list(label='spleen')
  File "/Users/akabynda/Diffuse_Steatoch/py_client/client_api.py", line 192, in model_list
    raise AIAAException(AIAAError.SERVER_ERROR, 'Status: {}; Response: {}'.format(status, response))
py_client.client_api.AIAAException: (3, "Status: 403; Response: b''")

I have followed all the instructions (https://docs.nvidia.com/clara/clara-train-sdk/pt/installation.html and https://docs.nvidia.com/clara/clara-train-sdk/aiaa/quickstart.html). Can you help me?

**Comment by SachidanandAlle** [comment]
Please use Monailabel.. 

https://github.com/Project-MONAI/MONAILabel

**Comment by lassoan** [comment]
If support for NVIDIA AIAA is ended then it could make sense to describe this in the README.md file, add a link to a page that describes how to achieve the same functionality with MONAILabel (especially how to install a shared MONAILabel server and install pre-trained models that were available in AIAA server) and [archive this repository](https://docs.github.com/en/repositories/archiving-a-github-repository).
