### ISSUE TITLE
NVIDIA AI-ASSISTED error

### ISSUE THREAD

**Issue by QianMuXiao** [NVIDIA/ai-assisted-annotation-client#107]
when I try to use this tools the 3D slicer show this window:
Traceback (most recent call last):
  File "C:/Users/xiaoqianmu/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/NvidiaAIAssistedAnnotation/lib/Slicer-5.2/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 198, in fetchAIAAModels
    models = self.logic.list_models()
  File "C:/Users/xiaoqianmu/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/NvidiaAIAssistedAnnotation/lib/Slicer-5.2/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 1076, in list_models
    return aiaaClient.model_list(label)
  File "C:\Users\xiaoqianmu\AppData\Local\NA-MIC\Slicer 5.2.2\NA-MIC\Extensions-31382\NvidiaAIAssistedAnnotation\lib\Slicer-5.2\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 192, in model_list
    raise AIAAException(AIAAError.SERVER_ERROR, 'Status: {}; Response: {}'.format(status, response))
NvidiaAIAAClientAPI.client_api.AIAAException: (3, "Status: 404; Response: b'<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'")

**Comment by diazandr3s** [comment]
Hi @QianMuXiao,

This tool is being deprecated. 
We are now supporting to MONAI Label: https://github.com/Project-MONAI/MONAILabel 

Thanks!

**Comment by QianMuXiao** [comment]
Thanks a lot @diazandr3s
