### ISSUE TITLE
Connection actively refused by server

### ISSUE THREAD

**Issue by cpinter** [NVIDIA/ai-assisted-annotation-client#35]
I tried using the extension, and did this:

* Load "CTA abdomen (Panoramix)" image from sample data module
* Create a segment in Segment Editor and rename it to Liver
* Switch to Nvidia AIAA effect, and set the server IP and port that I received from @SachidanandAlle
* Click Fetch Models

However I got a python error:
```
Traceback (most recent call last):
  File "C:/d/_Extensions/NvidiaAIAA/NvidiaAIAA/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 165, in onClickModels
    models = json.loads(logic.list_models(label if self.filterByLabel.checked else None))
  File "C:/d/_Extensions/NvidiaAIAA/NvidiaAIAA/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 472, in list_models
    conn.request('GET', selector)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\pinter\AppData\Local\NA-MIC\Slicer 4.11.0-2019-09-17\lib\Python\Lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

It says that the target machine actively refused the connection. Does anybody know anything about this? Thanks!

**Comment by SachidanandAlle** [comment]
Have you setup AIAA server?  Is it running.. if so, can you access http://<aiaa_server_ip>:<port>/v1/models... Is it accessible?  Can you can see the models.. If yes, then double check the configuration in plugin

**Comment by cpinter** [comment]
As I said I use the server the address of which I got from your email (on August 12, if you want to check it). If I enter that address in a browser it says it cannot be reached, also I cannot ping it. Maybe there is a different server now that should be used? The default value that the module has does not work either.

**Comment by SachidanandAlle** [comment]
I think you can check with @bsmarine he did mention earlier that server was down...

**Comment by lassoan** [comment]
@SachidanandAlle could you check if server of @bsmarine works for you or you get the same error as @cpinter?

**Comment by SachidanandAlle** [comment]
I cannot access now.. It was working earlier :)

**Comment by cpinter** [comment]
Thanks! Maybe it's just unlucky timing on my part. I'll wait until it's confirmed that it works again

**Comment by bsmarine** [comment]
Server should be back up and serving liver, liver tumor, liver vessels, and
a few other models now. Thanks for being patient!

**Comment by cpinter** [comment]
Thank you, I confirm it works now!
