### ISSUE TITLE
slicer error

### ISSUE THREAD

**Issue by anandmulay3** [NVIDIA/ai-assisted-annotation-client#74]
whenever I try to use this module in slicer I'm getting the following error,

`Traceback (most recent call last):
  File "C:/Users/anand.mulay/AppData/Roaming/NA-MIC/Extensions-29363/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 472, in onClickAnnotation
    result_file = self.logic.dextr3d(in_file, session_id, model, pointSet)
  File "C:/Users/anand.mulay/AppData/Roaming/NA-MIC/Extensions-29363/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 1053, in dextr3d
    session_id=session_id)
  File "C:\Users\anand.mulay\AppData\Roaming\NA-MIC\Extensions-29363\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 265, in dextr3d
    points, crop = AIAAUtils.image_pre_process(image_in, cropped_file, point_set, pad, roi_size)
  File "C:\Users\anand.mulay\AppData\Roaming\NA-MIC\Extensions-29363\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 567, in image_pre_process
    out_image = AIAAUtils.resample_image(cropped_image, target_size, True)
  File "C:\Users\anand.mulay\AppData\Roaming\NA-MIC\Extensions-29363\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 506, in resample_image
    return resample.Execute(itk_image)
  File "C:\Program Files\Slicer 4.11.0-2020-09-08\lib\Python\lib\site-packages\simpleitk-2.0.0rc3-py3.6-win-amd64.egg\SimpleITK\SimpleITK.py", line 20325, in Execute
    return _SimpleITK.ResampleImageFilter_Execute(self, image1)
RuntimeError: Exception thrown in SimpleITK ResampleImageFilter_Execute: D:\D\P\Slicer-0-build\ITK\Modules\Core\Common\include\itkImageBase.hxx:177:
itk::ERROR: itk::ERROR: Image(000001D711EAF140): A spacing of 0 is not allowed: Spacing is [0, 0, 1.58594]
`
I'm trying a script given my slicer developer gist,
https://gist.github.com/lassoan/ef30bc27a22a648ead7f82243f5cc7d5

here,am I missing something?

**Comment by SachidanandAlle** [comment]
there looks some issue in resample at your client side...
`A spacing of 0 is not allowed: Spacing is [0, 0, 1.58594]`

So, you can try some other samples (may be from https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2)

**Comment by anandmulay3** [comment]
thanks, i'll try the samples. 
Currently we didn't setup the AIAA server yet but it looks like I need to setup one soon 💯 .

**Comment by lassoan** [comment]
Just to clarify, the [AIAA Slicer plugin example](https://gist.github.com/lassoan/ef30bc27a22a648ead7f82243f5cc7d5) works well. The plugin slightly changed in since the first version of the example was created, but the latest version works with latest Slicer versions (I've just tried it using 3D Slicer version 4.11.0-2020-09-08 (revision 29363 / c565268) win-amd64). If you experience anything different then please comment here.

**Comment by XiaonanShao** [comment]
Nvidia AI-assisted annotation (AIAA) for 3D Slicer (4.11.20200930) has failed. I tried to delete and reinstall, but it still fails to start.
Operating system: WIN 10
Slicer version: 4.11.20200930
Today, when I opened the slicer, I found that the module could not be started. The program prompts no response.

**Comment by lassoan** [comment]
The default NVidia AIAA server that we set up for helping Slicer users is open for everyone. As a result, it is time-to-time overwhelmed with amount of requests. As of now, it is up and running.

If you find that anytime the server does not respond then wait some time (few ten minutes or few hours) and try again, or set up your own server (as described in the link provided in the documentation).
