### ISSUE TITLE
How to solve this error for Nvidia Ct tumor segmentation

### ISSUE THREAD

**Issue by akmal871026** [NVIDIA/ai-assisted-annotation-client#85]
Hi all, I got this error when trying to run the NVidia ct liver tumor segmentation. anyone can help me?

Traceback (most recent call last):
  File "C:/Users/Akmal/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 410, in onClickSegmentation
    extreme_points, result_file = self.logic.segmentation(in_file, session_id, model)
  File "C:/Users/Akmal/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 1092, in segmentation
    session_id=session_id,
  File "C:\Users\Akmal\AppData\Local\NA-MIC\Slicer 4.11.20210226\NA-MIC\Extensions-29738\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 389, in inference
    raise AIAAException(AIAAError.SERVER_ERROR, 'Status: {}; Response: {}'.format(status, form))
NvidiaAIAAClientAPI.client_api.AIAAException: (3, 'Status: 404; Response: b\'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\\n\'')

**Comment by YuanTingHsieh** [comment]
Looks like you are using 3D slicer.

Did you run your own AIAA server? If so, please share the logs of that.
Can you also share the screenshot of your 3D slicer with Nvidia AIAA plugin?

**Comment by akmal871026** [comment]
Yes can. Please whatsapp me 0143321631

**Comment by akmal871026** [comment]
Yes. Please whatsapp me 60143321631

**Comment by lassoan** [comment]
The default 3D Slicer segmentation server has been upgraded to Clara 4.0 and it supports all segmentation modes (auto-segmentation, segmentation from boundary points, and deepgrow), with many new models. It will be available the day after https://github.com/NVIDIA/ai-assisted-annotation-client/pull/88 is merged.

**Comment by JahanzebTariq** [comment]
@lassoan I'm getting this error every time I start the auto segmentation...Run Segmentation for model: clara_pt_brain_mri_segmentation_t1c - unexpected erro".. kindly resolve this issue
Traceback (most recent call last):
  File "E:/Slicer/Slicer 5.0.2/NA-MIC/Extensions-30822/NvidiaAIAssistedAnnotation/lib/Slicer-5.0/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 410, in onClickSegmentation
    extreme_points, result_file = self.logic.segmentation(in_file, session_id, model)
  File "E:/Slicer/Slicer 5.0.2/NA-MIC/Extensions-30822/NvidiaAIAssistedAnnotation/lib/Slicer-5.0/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py", line 1087, in segmentation
    params = aiaaClient.inference(
  File "E:\Slicer\Slicer 5.0.2\NA-MIC\Extensions-30822\NvidiaAIAssistedAnnotation\lib\Slicer-5.0\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 385, in inference
    status, form, files = AIAAUtils.http_multipart('POST', self._server_url, selector, in_fields, in_files)
  File "E:\Slicer\Slicer 5.0.2\NA-MIC\Extensions-30822\NvidiaAIAssistedAnnotation\lib\Slicer-5.0\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 647, in http_multipart
    content_type, body = AIAAUtils.encode_multipart_formdata(fields, files)
  File "E:\Slicer\Slicer 5.0.2\NA-MIC\Extensions-30822\NvidiaAIAssistedAnnotation\lib\Slicer-5.0\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py", line 715, in encode_multipart_formdata
    with open(filename, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Temp\\Slicer\\slicer-aiaa2022-06-29_08+58+27.394\\tmpi1vc3mhn.nii.gz'

**Comment by lassoan** [comment]
Does your username contain special (non-ASCII) characters?
What is your operating system version?

**Comment by JahanzebTariq** [comment]
Here are my pc specs

**Comment by lassoan** [comment]
@JahanzebTariq your response did not come through. Please post again.

**Comment by JahanzebTariq** [comment]
![image](https://user-images.githubusercontent.com/99289270/176481209-ec2529d8-5075-4a89-9b99-1c132aa902b8.png)
